# Generated by Django 5.0.2 on 2025-11-23 06:55

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_user_interests_user_phone_user_skills'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='activity',
            options={'ordering': ['-date']},
        ),
        migrations.AlterModelOptions(
            name='inscription',
            options={'ordering': ['-created_at']},
        ),
        migrations.AddField(
            model_name='activity',
            name='category',
            field=models.CharField(choices=[('environmental', 'Ambiental'), ('social', 'Social'), ('education', 'Educación'), ('health', 'Salud'), ('other', 'Otro')], default='other', max_length=20),
        ),
        migrations.AddField(
            model_name='activity',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='activity',
            name='end_time',
            field=models.TimeField(default='17:00'),
        ),
        migrations.AddField(
            model_name='activity',
            name='hours',
            field=models.DecimalField(decimal_places=1, default=4.0, help_text='Horas de duración', max_digits=4),
        ),
        migrations.AddField(
            model_name='activity',
            name='start_time',
            field=models.TimeField(default='09:00'),
        ),
        migrations.AddField(
            model_name='activity',
            name='status',
            field=models.CharField(choices=[('draft', 'Borrador'), ('published', 'Publicada'), ('completed', 'Completada'), ('cancelled', 'Cancelada')], default='published', max_length=20),
        ),
        migrations.AddField(
            model_name='inscription',
            name='attended',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='inscription',
            name='notes',
            field=models.TextField(blank=True, help_text='Notas del coordinador', null=True),
        ),
    ]
